// Major world airports with coordinates for map rendering
// ~100 airports covering all key global regions

export const AIRPORTS = [
  // ── Europe ──────────────────────────────────────────────────────────────
  {
    iata: 'LHR',
    name: 'Heathrow Airport',
    city: 'London',
    country: 'GB',
    lat: 51.4775,
    lng: -0.4614,
  },
  {
    iata: 'LGW',
    name: 'Gatwick Airport',
    city: 'London',
    country: 'GB',
    lat: 51.1537,
    lng: -0.1821,
  },
  { iata: 'STN', name: 'Stansted Airport', city: 'London', country: 'GB', lat: 51.885, lng: 0.235 },
  {
    iata: 'MAN',
    name: 'Manchester Airport',
    city: 'Manchester',
    country: 'GB',
    lat: 53.365,
    lng: -2.2728,
  },
  {
    iata: 'EDI',
    name: 'Edinburgh Airport',
    city: 'Edinburgh',
    country: 'GB',
    lat: 55.95,
    lng: -3.3725,
  },
  {
    iata: 'CDG',
    name: 'Charles de Gaulle Airport',
    city: 'Paris',
    country: 'FR',
    lat: 49.0097,
    lng: 2.5479,
  },
  {
    iata: 'ORY',
    name: 'Paris Orly Airport',
    city: 'Paris',
    country: 'FR',
    lat: 48.7253,
    lng: 2.3595,
  },
  {
    iata: 'LYS',
    name: 'Lyon-Saint-Exupéry Airport',
    city: 'Lyon',
    country: 'FR',
    lat: 45.7256,
    lng: 5.0811,
  },
  {
    iata: 'NCE',
    name: "Nice Côte d'Azur Airport",
    city: 'Nice',
    country: 'FR',
    lat: 43.6584,
    lng: 7.2159,
  },
  {
    iata: 'AMS',
    name: 'Amsterdam Schiphol Airport',
    city: 'Amsterdam',
    country: 'NL',
    lat: 52.3086,
    lng: 4.7639,
  },
  {
    iata: 'FRA',
    name: 'Frankfurt Airport',
    city: 'Frankfurt',
    country: 'DE',
    lat: 50.0333,
    lng: 8.5706,
  },
  {
    iata: 'MUC',
    name: 'Munich Airport',
    city: 'Munich',
    country: 'DE',
    lat: 48.3538,
    lng: 11.7861,
  },
  {
    iata: 'BER',
    name: 'Berlin Brandenburg Airport',
    city: 'Berlin',
    country: 'DE',
    lat: 52.3667,
    lng: 13.5033,
  },
  {
    iata: 'DUS',
    name: 'Düsseldorf Airport',
    city: 'Düsseldorf',
    country: 'DE',
    lat: 51.2895,
    lng: 6.7668,
  },
  {
    iata: 'HAM',
    name: 'Hamburg Airport',
    city: 'Hamburg',
    country: 'DE',
    lat: 53.6304,
    lng: 9.9882,
  },
  {
    iata: 'MAD',
    name: 'Adolfo Suárez Madrid–Barajas',
    city: 'Madrid',
    country: 'ES',
    lat: 40.4936,
    lng: -3.5668,
  },
  {
    iata: 'BCN',
    name: 'Josep Tarradellas Barcelona-El Prat',
    city: 'Barcelona',
    country: 'ES',
    lat: 41.2971,
    lng: 2.0785,
  },
  {
    iata: 'VLC',
    name: 'Valencia Airport',
    city: 'Valencia',
    country: 'ES',
    lat: 39.4893,
    lng: -0.4816,
  },
  {
    iata: 'SVQ',
    name: 'Seville Airport',
    city: 'Seville',
    country: 'ES',
    lat: 37.418,
    lng: -5.8931,
  },
  { iata: 'AGP', name: 'Málaga Airport', city: 'Málaga', country: 'ES', lat: 36.675, lng: -4.4991 },
  {
    iata: 'PMI',
    name: 'Palma de Mallorca Airport',
    city: 'Palma',
    country: 'ES',
    lat: 39.5517,
    lng: 2.7388,
  },
  {
    iata: 'FCO',
    name: 'Leonardo da Vinci–Fiumicino Airport',
    city: 'Rome',
    country: 'IT',
    lat: 41.8003,
    lng: 12.2389,
  },
  {
    iata: 'MXP',
    name: 'Malpensa Airport',
    city: 'Milan',
    country: 'IT',
    lat: 45.6306,
    lng: 8.7281,
  },
  { iata: 'LIN', name: 'Linate Airport', city: 'Milan', country: 'IT', lat: 45.4455, lng: 9.2773 },
  {
    iata: 'VCE',
    name: 'Venice Marco Polo Airport',
    city: 'Venice',
    country: 'IT',
    lat: 45.5053,
    lng: 12.3519,
  },
  {
    iata: 'NAP',
    name: 'Naples International Airport',
    city: 'Naples',
    country: 'IT',
    lat: 40.886,
    lng: 14.2908,
  },
  {
    iata: 'LIS',
    name: 'Humberto Delgado Airport',
    city: 'Lisbon',
    country: 'PT',
    lat: 38.7813,
    lng: -9.1359,
  },
  {
    iata: 'OPO',
    name: 'Francisco de Sá Carneiro Airport',
    city: 'Porto',
    country: 'PT',
    lat: 41.2481,
    lng: -8.6814,
  },
  { iata: 'FAO', name: 'Faro Airport', city: 'Faro', country: 'PT', lat: 37.0144, lng: -7.9659 },
  { iata: 'ZRH', name: 'Zurich Airport', city: 'Zurich', country: 'CH', lat: 47.4647, lng: 8.5492 },
  { iata: 'GVA', name: 'Geneva Airport', city: 'Geneva', country: 'CH', lat: 46.238, lng: 6.1089 },
  {
    iata: 'VIE',
    name: 'Vienna International Airport',
    city: 'Vienna',
    country: 'AT',
    lat: 48.1103,
    lng: 16.5697,
  },
  {
    iata: 'BRU',
    name: 'Brussels Airport',
    city: 'Brussels',
    country: 'BE',
    lat: 50.9014,
    lng: 4.4844,
  },
  {
    iata: 'CPH',
    name: 'Copenhagen Airport',
    city: 'Copenhagen',
    country: 'DK',
    lat: 55.6181,
    lng: 12.6561,
  },
  {
    iata: 'ARN',
    name: 'Stockholm Arlanda Airport',
    city: 'Stockholm',
    country: 'SE',
    lat: 59.6519,
    lng: 17.9186,
  },
  {
    iata: 'OSL',
    name: 'Oslo Gardermoen Airport',
    city: 'Oslo',
    country: 'NO',
    lat: 60.1939,
    lng: 11.1004,
  },
  {
    iata: 'HEL',
    name: 'Helsinki-Vantaa Airport',
    city: 'Helsinki',
    country: 'FI',
    lat: 60.3172,
    lng: 24.9633,
  },
  {
    iata: 'WAW',
    name: 'Warsaw Chopin Airport',
    city: 'Warsaw',
    country: 'PL',
    lat: 52.1657,
    lng: 20.9671,
  },
  { iata: 'DUB', name: 'Dublin Airport', city: 'Dublin', country: 'IE', lat: 53.4213, lng: -6.27 },
  {
    iata: 'ATH',
    name: 'Athens International Airport',
    city: 'Athens',
    country: 'GR',
    lat: 37.9364,
    lng: 23.9445,
  },
  {
    iata: 'SKG',
    name: 'Thessaloniki Airport',
    city: 'Thessaloniki',
    country: 'GR',
    lat: 40.5197,
    lng: 22.9709,
  },
  {
    iata: 'IST',
    name: 'Istanbul Airport',
    city: 'Istanbul',
    country: 'TR',
    lat: 41.2753,
    lng: 28.7519,
  },
  {
    iata: 'SAW',
    name: 'Sabiha Gökçen Airport',
    city: 'Istanbul',
    country: 'TR',
    lat: 40.8986,
    lng: 29.3092,
  },
  {
    iata: 'BUD',
    name: 'Budapest Liszt Ferenc Airport',
    city: 'Budapest',
    country: 'HU',
    lat: 47.4298,
    lng: 19.2611,
  },
  {
    iata: 'PRG',
    name: 'Václav Havel Airport Prague',
    city: 'Prague',
    country: 'CZ',
    lat: 50.1008,
    lng: 14.26,
  },
  {
    iata: 'OTP',
    name: 'Henri Coandă International Airport',
    city: 'Bucharest',
    country: 'RO',
    lat: 44.5711,
    lng: 26.0858,
  },
  { iata: 'SOF', name: 'Sofia Airport', city: 'Sofia', country: 'BG', lat: 42.6952, lng: 23.4114 },

  // ── Americas ─────────────────────────────────────────────────────────────
  {
    iata: 'JFK',
    name: 'John F. Kennedy International Airport',
    city: 'New York',
    country: 'US',
    lat: 40.6413,
    lng: -73.7781,
  },
  {
    iata: 'EWR',
    name: 'Newark Liberty International Airport',
    city: 'Newark',
    country: 'US',
    lat: 40.6895,
    lng: -74.1745,
  },
  {
    iata: 'LGA',
    name: 'LaGuardia Airport',
    city: 'New York',
    country: 'US',
    lat: 40.7769,
    lng: -73.874,
  },
  {
    iata: 'LAX',
    name: 'Los Angeles International Airport',
    city: 'Los Angeles',
    country: 'US',
    lat: 33.9425,
    lng: -118.4081,
  },
  {
    iata: 'ORD',
    name: "Chicago O'Hare International Airport",
    city: 'Chicago',
    country: 'US',
    lat: 41.9742,
    lng: -87.9073,
  },
  {
    iata: 'DFW',
    name: 'Dallas/Fort Worth International Airport',
    city: 'Dallas',
    country: 'US',
    lat: 32.8998,
    lng: -97.0403,
  },
  {
    iata: 'DEN',
    name: 'Denver International Airport',
    city: 'Denver',
    country: 'US',
    lat: 39.8561,
    lng: -104.6737,
  },
  {
    iata: 'ATL',
    name: 'Hartsfield-Jackson Atlanta International',
    city: 'Atlanta',
    country: 'US',
    lat: 33.6407,
    lng: -84.4277,
  },
  {
    iata: 'SFO',
    name: 'San Francisco International Airport',
    city: 'San Francisco',
    country: 'US',
    lat: 37.6213,
    lng: -122.379,
  },
  {
    iata: 'SEA',
    name: 'Seattle-Tacoma International Airport',
    city: 'Seattle',
    country: 'US',
    lat: 47.4502,
    lng: -122.3088,
  },
  {
    iata: 'MIA',
    name: 'Miami International Airport',
    city: 'Miami',
    country: 'US',
    lat: 25.7959,
    lng: -80.287,
  },
  {
    iata: 'BOS',
    name: 'Logan International Airport',
    city: 'Boston',
    country: 'US',
    lat: 42.3656,
    lng: -71.0096,
  },
  {
    iata: 'LAS',
    name: 'Harry Reid International Airport',
    city: 'Las Vegas',
    country: 'US',
    lat: 36.084,
    lng: -115.1537,
  },
  {
    iata: 'PHX',
    name: 'Phoenix Sky Harbor International Airport',
    city: 'Phoenix',
    country: 'US',
    lat: 33.4373,
    lng: -112.0078,
  },
  {
    iata: 'YYZ',
    name: 'Toronto Pearson International Airport',
    city: 'Toronto',
    country: 'CA',
    lat: 43.6777,
    lng: -79.6248,
  },
  {
    iata: 'YVR',
    name: 'Vancouver International Airport',
    city: 'Vancouver',
    country: 'CA',
    lat: 49.1967,
    lng: -123.1815,
  },
  {
    iata: 'YUL',
    name: 'Montréal–Trudeau International Airport',
    city: 'Montreal',
    country: 'CA',
    lat: 45.4706,
    lng: -73.7408,
  },
  {
    iata: 'MEX',
    name: 'Benito Juárez International Airport',
    city: 'Mexico City',
    country: 'MX',
    lat: 19.4363,
    lng: -99.0721,
  },
  {
    iata: 'CUN',
    name: 'Cancún International Airport',
    city: 'Cancún',
    country: 'MX',
    lat: 21.0365,
    lng: -86.8771,
  },
  {
    iata: 'GRU',
    name: 'Guarulhos International Airport',
    city: 'São Paulo',
    country: 'BR',
    lat: -23.4306,
    lng: -46.473,
  },
  {
    iata: 'GIG',
    name: 'Galeão International Airport',
    city: 'Rio de Janeiro',
    country: 'BR',
    lat: -22.81,
    lng: -43.2505,
  },
  {
    iata: 'EZE',
    name: 'Ministro Pistarini Airport',
    city: 'Buenos Aires',
    country: 'AR',
    lat: -34.8222,
    lng: -58.5358,
  },
  {
    iata: 'BOG',
    name: 'El Dorado International Airport',
    city: 'Bogotá',
    country: 'CO',
    lat: 4.7016,
    lng: -74.1469,
  },
  {
    iata: 'SCL',
    name: 'Arturo Merino Benítez Airport',
    city: 'Santiago',
    country: 'CL',
    lat: -33.393,
    lng: -70.7858,
  },
  {
    iata: 'LIM',
    name: 'Jorge Chávez International Airport',
    city: 'Lima',
    country: 'PE',
    lat: -12.0219,
    lng: -77.1143,
  },
  {
    iata: 'PTY',
    name: 'Tocumen International Airport',
    city: 'Panama City',
    country: 'PA',
    lat: 9.0714,
    lng: -79.3835,
  },

  // ── Asia-Pacific ─────────────────────────────────────────────────────────
  {
    iata: 'HND',
    name: 'Tokyo Haneda Airport',
    city: 'Tokyo',
    country: 'JP',
    lat: 35.5494,
    lng: 139.7798,
  },
  {
    iata: 'NRT',
    name: 'Narita International Airport',
    city: 'Tokyo',
    country: 'JP',
    lat: 35.7647,
    lng: 140.3864,
  },
  {
    iata: 'KIX',
    name: 'Kansai International Airport',
    city: 'Osaka',
    country: 'JP',
    lat: 34.4347,
    lng: 135.244,
  },
  {
    iata: 'PEK',
    name: 'Beijing Capital International Airport',
    city: 'Beijing',
    country: 'CN',
    lat: 40.0799,
    lng: 116.6031,
  },
  {
    iata: 'PVG',
    name: 'Shanghai Pudong International Airport',
    city: 'Shanghai',
    country: 'CN',
    lat: 31.1443,
    lng: 121.8083,
  },
  {
    iata: 'CAN',
    name: 'Guangzhou Baiyun International Airport',
    city: 'Guangzhou',
    country: 'CN',
    lat: 23.3924,
    lng: 113.299,
  },
  {
    iata: 'HKG',
    name: 'Hong Kong International Airport',
    city: 'Hong Kong',
    country: 'HK',
    lat: 22.308,
    lng: 113.9185,
  },
  {
    iata: 'SIN',
    name: 'Singapore Changi Airport',
    city: 'Singapore',
    country: 'SG',
    lat: 1.3644,
    lng: 103.9915,
  },
  {
    iata: 'BKK',
    name: 'Suvarnabhumi Airport',
    city: 'Bangkok',
    country: 'TH',
    lat: 13.6811,
    lng: 100.7478,
  },
  {
    iata: 'ICN',
    name: 'Incheon International Airport',
    city: 'Seoul',
    country: 'KR',
    lat: 37.4602,
    lng: 126.4407,
  },
  {
    iata: 'KUL',
    name: 'Kuala Lumpur International Airport',
    city: 'Kuala Lumpur',
    country: 'MY',
    lat: 2.7456,
    lng: 101.7099,
  },
  {
    iata: 'CGK',
    name: 'Soekarno-Hatta International Airport',
    city: 'Jakarta',
    country: 'ID',
    lat: -6.1256,
    lng: 106.6559,
  },
  {
    iata: 'SYD',
    name: 'Sydney Kingsford Smith Airport',
    city: 'Sydney',
    country: 'AU',
    lat: -33.9461,
    lng: 151.1772,
  },
  {
    iata: 'MEL',
    name: 'Melbourne Airport',
    city: 'Melbourne',
    country: 'AU',
    lat: -37.669,
    lng: 144.841,
  },
  {
    iata: 'BNE',
    name: 'Brisbane Airport',
    city: 'Brisbane',
    country: 'AU',
    lat: -27.3842,
    lng: 153.1175,
  },
  {
    iata: 'PER',
    name: 'Perth Airport',
    city: 'Perth',
    country: 'AU',
    lat: -31.9403,
    lng: 115.9669,
  },
  {
    iata: 'AKL',
    name: 'Auckland Airport',
    city: 'Auckland',
    country: 'NZ',
    lat: -37.0082,
    lng: 174.785,
  },
  {
    iata: 'DEL',
    name: 'Indira Gandhi International Airport',
    city: 'New Delhi',
    country: 'IN',
    lat: 28.5562,
    lng: 77.1,
  },
  {
    iata: 'BOM',
    name: 'Chhatrapati Shivaji Maharaj International',
    city: 'Mumbai',
    country: 'IN',
    lat: 19.0896,
    lng: 72.8656,
  },
  {
    iata: 'BLR',
    name: 'Kempegowda International Airport',
    city: 'Bengaluru',
    country: 'IN',
    lat: 13.1986,
    lng: 77.7066,
  },
  {
    iata: 'MAA',
    name: 'Chennai International Airport',
    city: 'Chennai',
    country: 'IN',
    lat: 12.9941,
    lng: 80.1709,
  },
  {
    iata: 'MNL',
    name: 'Ninoy Aquino International Airport',
    city: 'Manila',
    country: 'PH',
    lat: 14.5086,
    lng: 121.0197,
  },
  {
    iata: 'TPE',
    name: 'Taiwan Taoyuan International Airport',
    city: 'Taipei',
    country: 'TW',
    lat: 25.0777,
    lng: 121.2326,
  },
  {
    iata: 'HAN',
    name: 'Noi Bai International Airport',
    city: 'Hanoi',
    country: 'VN',
    lat: 21.2212,
    lng: 105.8072,
  },
  {
    iata: 'SGN',
    name: 'Tan Son Nhat International Airport',
    city: 'Ho Chi Minh City',
    country: 'VN',
    lat: 10.8188,
    lng: 106.6519,
  },

  // ── Middle East & Africa ─────────────────────────────────────────────────
  {
    iata: 'DXB',
    name: 'Dubai International Airport',
    city: 'Dubai',
    country: 'AE',
    lat: 25.2532,
    lng: 55.3657,
  },
  {
    iata: 'AUH',
    name: 'Abu Dhabi International Airport',
    city: 'Abu Dhabi',
    country: 'AE',
    lat: 24.433,
    lng: 54.6511,
  },
  {
    iata: 'DOH',
    name: 'Hamad International Airport',
    city: 'Doha',
    country: 'QA',
    lat: 25.2608,
    lng: 51.6138,
  },
  {
    iata: 'RUH',
    name: 'King Khalid International Airport',
    city: 'Riyadh',
    country: 'SA',
    lat: 24.9576,
    lng: 46.6988,
  },
  {
    iata: 'JED',
    name: 'King Abdulaziz International Airport',
    city: 'Jeddah',
    country: 'SA',
    lat: 21.6796,
    lng: 39.1565,
  },
  {
    iata: 'AMM',
    name: 'Queen Alia International Airport',
    city: 'Amman',
    country: 'JO',
    lat: 31.7226,
    lng: 35.9932,
  },
  {
    iata: 'TLV',
    name: 'Ben Gurion International Airport',
    city: 'Tel Aviv',
    country: 'IL',
    lat: 32.0114,
    lng: 34.8867,
  },
  {
    iata: 'CAI',
    name: 'Cairo International Airport',
    city: 'Cairo',
    country: 'EG',
    lat: 30.1219,
    lng: 31.4056,
  },
  {
    iata: 'CMN',
    name: 'Mohammed V International Airport',
    city: 'Casablanca',
    country: 'MA',
    lat: 33.3675,
    lng: -7.5898,
  },
  {
    iata: 'TUN',
    name: 'Tunis-Carthage International Airport',
    city: 'Tunis',
    country: 'TN',
    lat: 36.851,
    lng: 10.2272,
  },
  {
    iata: 'CPT',
    name: 'Cape Town International Airport',
    city: 'Cape Town',
    country: 'ZA',
    lat: -33.9715,
    lng: 18.6021,
  },
  {
    iata: 'JNB',
    name: 'O.R. Tambo International Airport',
    city: 'Johannesburg',
    country: 'ZA',
    lat: -26.1367,
    lng: 28.2411,
  },
  {
    iata: 'NBO',
    name: 'Jomo Kenyatta International Airport',
    city: 'Nairobi',
    country: 'KE',
    lat: -1.3192,
    lng: 36.9275,
  },
  {
    iata: 'ADD',
    name: 'Addis Ababa Bole International Airport',
    city: 'Addis Ababa',
    country: 'ET',
    lat: 8.9779,
    lng: 38.7993,
  },
  {
    iata: 'LOS',
    name: 'Murtala Muhammed International Airport',
    city: 'Lagos',
    country: 'NG',
    lat: 6.5774,
    lng: 3.3212,
  },
  {
    iata: 'ACC',
    name: 'Kotoka International Airport',
    city: 'Accra',
    country: 'GH',
    lat: 5.6052,
    lng: -0.1668,
  },
]

// O(1) lookup by IATA code
export const AIRPORT_MAP = Object.fromEntries(AIRPORTS.map(a => [a.iata, a]))

/**
 * Look up a single airport by IATA code (case-insensitive).
 * Returns null if not found.
 */
export function getAirport(iata) {
  if (!iata) return null
  return AIRPORT_MAP[iata.toUpperCase()] ?? null
}

/**
 * Search airports by text (matches IATA, city, name).
 * Returns top `limit` results.
 */
export function searchAirports(query, limit = 8) {
  if (!query || query.length < 1) return []
  const q = query.toLowerCase()
  return AIRPORTS.filter(
    a =>
      a.iata.toLowerCase().startsWith(q) ||
      a.city.toLowerCase().includes(q) ||
      a.name.toLowerCase().includes(q) ||
      a.country.toLowerCase().includes(q)
  ).slice(0, limit)
}
