/**
 * Mock data that mirrors Amadeus API response format.
 * Used when AMADEUS_MOCK_MODE=true (no credentials needed).
 */

const TODAY = new Date()
const d = (daysOffset, hour = 8, min = 0) => {
  const dt = new Date(TODAY)
  dt.setDate(dt.getDate() + daysOffset)
  dt.setHours(hour, min, 0, 0)
  return dt.toISOString().slice(0, 19)
}

// Airlines dictionary
export const MOCK_AIRLINES = {
  IB: 'Iberia',
  VY: 'Vueling',
  FR: 'Ryanair',
  U2: 'easyJet',
  BA: 'British Airways',
  AF: 'Air France',
  LH: 'Lufthansa',
  KL: 'KLM',
  EK: 'Emirates',
  QR: 'Qatar Airways',
  AA: 'American Airlines',
  UA: 'United Airlines',
  DL: 'Delta Air Lines',
  AY: 'Finnair',
  SK: 'SAS',
  OS: 'Austrian Airlines',
  SN: 'Brussels Airlines',
  TP: 'TAP Air Portugal',
  VB: 'VivaAerobus',
  AM: 'Aeromexico',
}

/** Build a mock flight offer */
function offer({
  id,
  origin,
  destination,
  departAt,
  arriveAt,
  carrier,
  flightNum,
  totalPrice,
  currency = 'EUR',
  stops = 0,
  duration,
  returnDepartAt,
  returnArriveAt,
  returnCarrier,
  returnFlightNum,
  returnDuration,
  aircraft = '32A',
}) {
  const itineraries = [
    {
      duration: duration ?? 'PT2H0M',
      segments: [
        {
          departure: { iataCode: origin, at: departAt },
          arrival: { iataCode: destination, at: arriveAt },
          carrierCode: carrier,
          number: flightNum,
          aircraft: { code: aircraft },
          operating: { carrierCode: carrier },
          duration: duration ?? 'PT2H0M',
          id: `${id}-1`,
          numberOfStops: stops,
        },
      ],
    },
  ]

  if (returnDepartAt) {
    itineraries.push({
      duration: returnDuration ?? duration ?? 'PT2H0M',
      segments: [
        {
          departure: { iataCode: destination, at: returnDepartAt },
          arrival: { iataCode: origin, at: returnArriveAt },
          carrierCode: returnCarrier ?? carrier,
          number: returnFlightNum ?? flightNum,
          aircraft: { code: aircraft },
          operating: { carrierCode: returnCarrier ?? carrier },
          duration: returnDuration ?? duration ?? 'PT2H0M',
          id: `${id}-2`,
          numberOfStops: stops,
        },
      ],
    })
  }

  return {
    type: 'flight-offer',
    id: String(id),
    source: 'GDS',
    instantTicketingRequired: false,
    nonHomogeneous: false,
    oneWay: !returnDepartAt,
    numberOfBookableSeats: Math.floor(Math.random() * 7) + 3,
    itineraries,
    price: {
      currency,
      total: String(totalPrice),
      base: String(Math.round(totalPrice * 0.82)),
      grandTotal: String(totalPrice),
    },
    validatingAirlineCodes: [carrier],
    travelerPricings: [
      {
        travelerId: '1',
        fareOption: 'STANDARD',
        travelerType: 'ADULT',
        price: { currency, total: String(totalPrice), base: String(Math.round(totalPrice * 0.82)) },
        fareDetailsBySegment: [
          {
            segmentId: `${id}-1`,
            cabin: 'ECONOMY',
            fareBasis: 'YLOWE',
            class: 'Y',
            includedCheckedBags: { quantity: stops > 0 ? 1 : 0 },
          },
        ],
      },
    ],
  }
}

/** Generate mock results for MAD origin */
const MAD_OFFERS = [
  offer({
    id: 1,
    origin: 'MAD',
    destination: 'BCN',
    departAt: d(7, 8, 0),
    arriveAt: d(7, 9, 20),
    carrier: 'VY',
    flightNum: '1820',
    totalPrice: 49,
    duration: 'PT1H20M',
    returnDepartAt: d(14, 19, 0),
    returnArriveAt: d(14, 20, 20),
    returnFlightNum: '1823',
    returnDuration: 'PT1H20M',
  }),
  offer({
    id: 2,
    origin: 'MAD',
    destination: 'LIS',
    departAt: d(7, 9, 30),
    arriveAt: d(7, 10, 45),
    carrier: 'IB',
    flightNum: '3822',
    totalPrice: 69,
    duration: 'PT1H15M',
    returnDepartAt: d(14, 12, 0),
    returnArriveAt: d(14, 13, 15),
  }),
  offer({
    id: 3,
    origin: 'MAD',
    destination: 'LHR',
    departAt: d(7, 7, 15),
    arriveAt: d(7, 9, 35),
    carrier: 'IB',
    flightNum: '3170',
    totalPrice: 89,
    duration: 'PT2H20M',
    returnDepartAt: d(14, 18, 0),
    returnArriveAt: d(14, 20, 25),
    returnFlightNum: '3171',
    returnDuration: 'PT2H25M',
  }),
  offer({
    id: 4,
    origin: 'MAD',
    destination: 'CDG',
    departAt: d(7, 6, 50),
    arriveAt: d(7, 9, 0),
    carrier: 'AF',
    flightNum: '1001',
    totalPrice: 95,
    duration: 'PT2H10M',
    returnDepartAt: d(14, 15, 0),
    returnArriveAt: d(14, 17, 15),
    returnCarrier: 'IB',
    returnFlightNum: '3554',
    returnDuration: 'PT2H15M',
  }),
  offer({
    id: 5,
    origin: 'MAD',
    destination: 'FCO',
    departAt: d(7, 8, 0),
    arriveAt: d(7, 10, 30),
    carrier: 'IB',
    flightNum: '3460',
    totalPrice: 105,
    duration: 'PT2H30M',
    returnDepartAt: d(14, 14, 0),
    returnArriveAt: d(14, 16, 35),
    returnFlightNum: '3461',
  }),
  offer({
    id: 6,
    origin: 'MAD',
    destination: 'AMS',
    departAt: d(7, 7, 30),
    arriveAt: d(7, 10, 10),
    carrier: 'KL',
    flightNum: '1705',
    totalPrice: 119,
    duration: 'PT2H40M',
    returnDepartAt: d(14, 17, 0),
    returnArriveAt: d(14, 19, 45),
    returnFlightNum: '1706',
    aircraft: '73H',
  }),
  offer({
    id: 7,
    origin: 'MAD',
    destination: 'FRA',
    departAt: d(7, 6, 40),
    arriveAt: d(7, 9, 30),
    carrier: 'LH',
    flightNum: '1801',
    totalPrice: 129,
    duration: 'PT2H50M',
    returnDepartAt: d(14, 16, 0),
    returnArriveAt: d(14, 19, 0),
    returnFlightNum: '1800',
  }),
  offer({
    id: 8,
    origin: 'MAD',
    destination: 'MXP',
    departAt: d(7, 9, 0),
    arriveAt: d(7, 11, 40),
    carrier: 'VY',
    flightNum: '6152',
    totalPrice: 79,
    duration: 'PT2H40M',
    returnDepartAt: d(14, 13, 0),
    returnArriveAt: d(14, 15, 45),
    returnFlightNum: '6153',
  }),
  offer({
    id: 9,
    origin: 'MAD',
    destination: 'DXB',
    departAt: d(7, 22, 30),
    arriveAt: d(8, 8, 0),
    carrier: 'EK',
    flightNum: '141',
    totalPrice: 389,
    duration: 'PT7H30M',
    returnDepartAt: d(14, 10, 0),
    returnArriveAt: d(14, 15, 30),
    returnCarrier: 'EK',
    returnFlightNum: '142',
    returnDuration: 'PT7H30M',
    aircraft: '388',
  }),
  offer({
    id: 10,
    origin: 'MAD',
    destination: 'JFK',
    departAt: d(7, 11, 0),
    arriveAt: d(7, 14, 15),
    carrier: 'IB',
    flightNum: '6251',
    totalPrice: 489,
    duration: 'PT9H15M',
    returnDepartAt: d(14, 17, 0),
    returnArriveAt: d(15, 7, 20),
    returnFlightNum: '6252',
    returnDuration: 'PT8H20M',
    aircraft: '333',
  }),
  offer({
    id: 11,
    origin: 'MAD',
    destination: 'GRU',
    departAt: d(7, 23, 55),
    arriveAt: d(8, 9, 0),
    carrier: 'IB',
    flightNum: '6841',
    totalPrice: 599,
    duration: 'PT11H5M',
    returnDepartAt: d(14, 22, 0),
    returnArriveAt: d(15, 14, 20),
    returnFlightNum: '6842',
    returnDuration: 'PT14H20M',
    aircraft: '333',
  }),
  offer({
    id: 12,
    origin: 'MAD',
    destination: 'MEX',
    departAt: d(7, 12, 0),
    arriveAt: d(7, 17, 30),
    carrier: 'IB',
    flightNum: '6403',
    totalPrice: 549,
    duration: 'PT11H30M',
    returnDepartAt: d(14, 19, 30),
    returnArriveAt: d(15, 13, 20),
    returnFlightNum: '6404',
    returnDuration: 'PT11H50M',
    aircraft: '340',
  }),
  offer({
    id: 13,
    origin: 'MAD',
    destination: 'NRT',
    departAt: d(7, 9, 0),
    arriveAt: d(8, 5, 30),
    carrier: 'IB',
    flightNum: '6017',
    totalPrice: 789,
    stops: 1,
    duration: 'PT14H30M',
    returnDepartAt: d(14, 12, 0),
    returnArriveAt: d(15, 12, 0),
    returnFlightNum: '6018',
    returnDuration: 'PT16H0M',
    aircraft: '333',
  }),
  offer({
    id: 14,
    origin: 'MAD',
    destination: 'PMI',
    departAt: d(7, 7, 0),
    arriveAt: d(7, 8, 20),
    carrier: 'VY',
    flightNum: '3930',
    totalPrice: 55,
    duration: 'PT1H20M',
    returnDepartAt: d(14, 20, 0),
    returnArriveAt: d(14, 21, 20),
    returnFlightNum: '3931',
  }),
  offer({
    id: 15,
    origin: 'MAD',
    destination: 'ATH',
    departAt: d(7, 6, 0),
    arriveAt: d(7, 10, 40),
    carrier: 'IB',
    flightNum: '3680',
    totalPrice: 149,
    duration: 'PT4H40M',
    returnDepartAt: d(14, 11, 0),
    returnArriveAt: d(14, 15, 50),
    returnFlightNum: '3681',
  }),
  offer({
    id: 16,
    origin: 'MAD',
    destination: 'IST',
    departAt: d(7, 7, 0),
    arriveAt: d(7, 12, 40),
    carrier: 'IB',
    flightNum: '3710',
    totalPrice: 175,
    duration: 'PT5H40M',
    stops: 1,
    returnDepartAt: d(14, 14, 0),
    returnArriveAt: d(14, 20, 10),
    returnFlightNum: '3711',
  }),
  offer({
    id: 17,
    origin: 'MAD',
    destination: 'LAX',
    departAt: d(7, 11, 0),
    arriveAt: d(7, 13, 40),
    carrier: 'IB',
    flightNum: '6273',
    stops: 1,
    totalPrice: 649,
    duration: 'PT14H40M',
    returnDepartAt: d(14, 16, 0),
    returnArriveAt: d(15, 13, 50),
    returnFlightNum: '6274',
    returnDuration: 'PT15H50M',
    aircraft: '333',
  }),
  offer({
    id: 18,
    origin: 'MAD',
    destination: 'DOH',
    departAt: d(7, 7, 30),
    arriveAt: d(7, 14, 0),
    carrier: 'QR',
    flightNum: '148',
    totalPrice: 349,
    duration: 'PT6H30M',
    returnDepartAt: d(14, 15, 0),
    returnArriveAt: d(14, 21, 0),
    returnFlightNum: '149',
    aircraft: '359',
  }),
  offer({
    id: 19,
    origin: 'MAD',
    destination: 'CMN',
    departAt: d(7, 9, 0),
    arriveAt: d(7, 10, 30),
    carrier: 'IB',
    flightNum: '3740',
    totalPrice: 89,
    duration: 'PT1H30M',
    returnDepartAt: d(14, 11, 0),
    returnArriveAt: d(14, 12, 30),
    returnFlightNum: '3741',
  }),
  offer({
    id: 20,
    origin: 'MAD',
    destination: 'SIN',
    departAt: d(7, 23, 0),
    arriveAt: d(8, 17, 20),
    carrier: 'QR',
    flightNum: '148',
    stops: 1,
    totalPrice: 699,
    duration: 'PT16H20M',
    returnDepartAt: d(14, 1, 30),
    returnArriveAt: d(15, 7, 30),
    returnFlightNum: '149',
    returnDuration: 'PT18H0M',
    aircraft: '359',
  }),
]

/** Generate mock results for LHR origin */
const LHR_OFFERS = [
  offer({
    id: 101,
    origin: 'LHR',
    destination: 'JFK',
    departAt: d(7, 9, 0),
    arriveAt: d(7, 12, 0),
    carrier: 'BA',
    flightNum: '117',
    totalPrice: 349,
    duration: 'PT8H0M',
    currency: 'GBP',
    returnDepartAt: d(14, 18, 30),
    returnArriveAt: d(15, 6, 40),
    returnFlightNum: '118',
    aircraft: '77W',
  }),
  offer({
    id: 102,
    origin: 'LHR',
    destination: 'CDG',
    departAt: d(7, 7, 0),
    arriveAt: d(7, 9, 15),
    carrier: 'BA',
    flightNum: '304',
    totalPrice: 89,
    currency: 'GBP',
    duration: 'PT1H15M',
    returnDepartAt: d(14, 16, 0),
    returnArriveAt: d(14, 18, 20),
    returnFlightNum: '307',
  }),
  offer({
    id: 103,
    origin: 'LHR',
    destination: 'DXB',
    departAt: d(7, 21, 30),
    arriveAt: d(8, 8, 30),
    carrier: 'EK',
    flightNum: '3',
    totalPrice: 399,
    currency: 'GBP',
    duration: 'PT7H0M',
    returnDepartAt: d(14, 3, 15),
    returnArriveAt: d(14, 8, 15),
    returnFlightNum: '4',
    aircraft: '380',
  }),
  offer({
    id: 104,
    origin: 'LHR',
    destination: 'SIN',
    departAt: d(7, 21, 15),
    arriveAt: d(8, 17, 15),
    carrier: 'BA',
    flightNum: '11',
    totalPrice: 569,
    currency: 'GBP',
    duration: 'PT12H0M',
    returnDepartAt: d(14, 23, 45),
    returnArriveAt: d(15, 6, 15),
    returnFlightNum: '12',
    aircraft: '77W',
  }),
  offer({
    id: 105,
    origin: 'LHR',
    destination: 'AMS',
    departAt: d(7, 6, 30),
    arriveAt: d(7, 8, 55),
    carrier: 'BA',
    flightNum: '428',
    totalPrice: 69,
    currency: 'GBP',
    duration: 'PT1H25M',
    returnDepartAt: d(14, 18, 0),
    returnArriveAt: d(14, 20, 25),
    returnFlightNum: '433',
  }),
  offer({
    id: 106,
    origin: 'LHR',
    destination: 'NRT',
    departAt: d(7, 11, 0),
    arriveAt: d(8, 7, 55),
    carrier: 'BA',
    flightNum: '5',
    totalPrice: 689,
    currency: 'GBP',
    duration: 'PT12H55M',
    returnDepartAt: d(14, 12, 55),
    returnArriveAt: d(15, 17, 55),
    returnFlightNum: '6',
    aircraft: '789',
  }),
  offer({
    id: 107,
    origin: 'LHR',
    destination: 'MAD',
    departAt: d(7, 7, 30),
    arriveAt: d(7, 10, 55),
    carrier: 'BA',
    flightNum: '460',
    totalPrice: 99,
    currency: 'GBP',
    duration: 'PT2H25M',
    returnDepartAt: d(14, 11, 30),
    returnArriveAt: d(14, 15, 0),
    returnFlightNum: '461',
  }),
  offer({
    id: 108,
    origin: 'LHR',
    destination: 'FCO',
    departAt: d(7, 7, 0),
    arriveAt: d(7, 10, 25),
    carrier: 'BA',
    flightNum: '550',
    totalPrice: 149,
    currency: 'GBP',
    duration: 'PT2H25M',
    returnDepartAt: d(14, 12, 30),
    returnArriveAt: d(14, 15, 55),
    returnFlightNum: '551',
  }),
]

/** Generate mock results for JFK origin */
const JFK_OFFERS = [
  offer({
    id: 201,
    origin: 'JFK',
    destination: 'LHR',
    departAt: d(7, 22, 0),
    arriveAt: d(8, 10, 30),
    carrier: 'AA',
    flightNum: '100',
    totalPrice: 449,
    currency: 'USD',
    duration: 'PT7H30M',
    returnDepartAt: d(14, 11, 0),
    returnArriveAt: d(14, 14, 0),
    returnFlightNum: '101',
    aircraft: '77W',
  }),
  offer({
    id: 202,
    origin: 'JFK',
    destination: 'CDG',
    departAt: d(7, 23, 30),
    arriveAt: d(8, 13, 15),
    carrier: 'AA',
    flightNum: '44',
    totalPrice: 399,
    currency: 'USD',
    duration: 'PT7H45M',
    returnDepartAt: d(14, 14, 25),
    returnArriveAt: d(14, 17, 10),
    returnFlightNum: '45',
    aircraft: '77W',
  }),
  offer({
    id: 203,
    origin: 'JFK',
    destination: 'DXB',
    departAt: d(7, 22, 0),
    arriveAt: d(8, 19, 10),
    carrier: 'EK',
    flightNum: '202',
    totalPrice: 699,
    currency: 'USD',
    duration: 'PT13H10M',
    returnDepartAt: d(14, 21, 30),
    returnArriveAt: d(15, 3, 55),
    returnFlightNum: '201',
    aircraft: '388',
  }),
  offer({
    id: 204,
    origin: 'JFK',
    destination: 'GRU',
    departAt: d(7, 20, 0),
    arriveAt: d(8, 7, 30),
    carrier: 'AA',
    flightNum: '934',
    totalPrice: 529,
    currency: 'USD',
    duration: 'PT9H30M',
    returnDepartAt: d(14, 10, 0),
    returnArriveAt: d(14, 21, 55),
    returnFlightNum: '935',
    aircraft: '763',
  }),
  offer({
    id: 205,
    origin: 'JFK',
    destination: 'LAX',
    departAt: d(7, 6, 0),
    arriveAt: d(7, 9, 30),
    carrier: 'AA',
    flightNum: '1',
    totalPrice: 149,
    currency: 'USD',
    duration: 'PT5H30M',
    returnDepartAt: d(14, 11, 0),
    returnArriveAt: d(14, 19, 25),
    returnFlightNum: '2',
    aircraft: '321',
  }),
  offer({
    id: 206,
    origin: 'JFK',
    destination: 'NRT',
    departAt: d(7, 12, 30),
    arriveAt: d(8, 15, 30),
    carrier: 'AA',
    flightNum: '169',
    totalPrice: 799,
    currency: 'USD',
    duration: 'PT14H0M',
    stops: 1,
    returnDepartAt: d(14, 17, 0),
    returnArriveAt: d(15, 17, 0),
    returnFlightNum: '170',
    aircraft: '777',
  }),
  offer({
    id: 207,
    origin: 'JFK',
    destination: 'MEX',
    departAt: d(7, 7, 0),
    arriveAt: d(7, 11, 0),
    carrier: 'AA',
    flightNum: '193',
    totalPrice: 299,
    currency: 'USD',
    duration: 'PT4H0M',
    returnDepartAt: d(14, 12, 0),
    returnArriveAt: d(14, 17, 25),
    returnFlightNum: '192',
  }),
  offer({
    id: 208,
    origin: 'JFK',
    destination: 'MAD',
    departAt: d(7, 23, 55),
    arriveAt: d(8, 11, 40),
    carrier: 'IB',
    flightNum: '6252',
    totalPrice: 519,
    currency: 'USD',
    duration: 'PT7H45M',
    returnDepartAt: d(14, 11, 0),
    returnArriveAt: d(14, 14, 15),
    returnFlightNum: '6251',
    aircraft: '333',
  }),
]

// Map origin → offers
const OFFERS_BY_ORIGIN = {
  MAD: MAD_OFFERS,
  LHR: LHR_OFFERS,
  JFK: JFK_OFFERS,
}

/**
 * Generate mock flight-offers response for given params.
 * Filters by destination if provided, randomizes prices slightly.
 */
export function mockFlightOffersResponse({ originLocationCode, destinationLocationCode }) {
  const origin = originLocationCode?.toUpperCase()
  let results = OFFERS_BY_ORIGIN[origin] ?? MAD_OFFERS

  if (destinationLocationCode) {
    const dest = destinationLocationCode.toUpperCase()
    results = results.filter(o =>
      o.itineraries[0]?.segments?.some(s => s.arrival.iataCode === dest)
    )
  }

  // Add slight price variance for realism
  const varied = results.map(o => ({
    ...o,
    price: {
      ...o.price,
      total: String(Math.round(parseFloat(o.price.total) * (0.92 + Math.random() * 0.16))),
    },
  }))

  return {
    meta: { count: varied.length, links: { self: '' } },
    data: varied,
    dictionaries: {
      carriers: MOCK_AIRLINES,
      aircraft: {
        '32A': 'AIRBUS A320',
        '73H': 'BOEING 737',
        333: 'AIRBUS A330-300',
        388: 'AIRBUS A380-800',
        '77W': 'BOEING 777-300ER',
        789: 'BOEING 787-9',
        359: 'AIRBUS A350-900',
      },
    },
  }
}

/**
 * Generate mock locations response for given query.
 */
export function mockLocationsResponse(query) {
  // Return a simple subset of airports matching the query
  const STATIC = [
    { iataCode: 'MAD', name: 'Madrid Barajas', cityName: 'Madrid', countryCode: 'ES' },
    { iataCode: 'BCN', name: 'Barcelona El Prat', cityName: 'Barcelona', countryCode: 'ES' },
    { iataCode: 'LHR', name: 'London Heathrow', cityName: 'London', countryCode: 'GB' },
    { iataCode: 'LGW', name: 'London Gatwick', cityName: 'London', countryCode: 'GB' },
    { iataCode: 'CDG', name: 'Paris Charles de Gaulle', cityName: 'Paris', countryCode: 'FR' },
    { iataCode: 'AMS', name: 'Amsterdam Schiphol', cityName: 'Amsterdam', countryCode: 'NL' },
    { iataCode: 'FRA', name: 'Frankfurt Airport', cityName: 'Frankfurt', countryCode: 'DE' },
    { iataCode: 'MUC', name: 'Munich Airport', cityName: 'Munich', countryCode: 'DE' },
    { iataCode: 'FCO', name: 'Rome Fiumicino', cityName: 'Rome', countryCode: 'IT' },
    { iataCode: 'MXP', name: 'Milan Malpensa', cityName: 'Milan', countryCode: 'IT' },
    { iataCode: 'LIS', name: 'Lisbon Portela', cityName: 'Lisbon', countryCode: 'PT' },
    { iataCode: 'ZRH', name: 'Zurich Airport', cityName: 'Zurich', countryCode: 'CH' },
    { iataCode: 'VIE', name: 'Vienna International', cityName: 'Vienna', countryCode: 'AT' },
    { iataCode: 'JFK', name: 'New York JFK', cityName: 'New York', countryCode: 'US' },
    {
      iataCode: 'LAX',
      name: 'Los Angeles International',
      cityName: 'Los Angeles',
      countryCode: 'US',
    },
    { iataCode: 'DXB', name: 'Dubai International', cityName: 'Dubai', countryCode: 'AE' },
    { iataCode: 'DOH', name: 'Hamad International', cityName: 'Doha', countryCode: 'QA' },
    { iataCode: 'SIN', name: 'Singapore Changi', cityName: 'Singapore', countryCode: 'SG' },
    { iataCode: 'NRT', name: 'Tokyo Narita', cityName: 'Tokyo', countryCode: 'JP' },
    { iataCode: 'HND', name: 'Tokyo Haneda', cityName: 'Tokyo', countryCode: 'JP' },
    { iataCode: 'GRU', name: 'São Paulo Guarulhos', cityName: 'São Paulo', countryCode: 'BR' },
    {
      iataCode: 'MEX',
      name: 'Mexico City International',
      cityName: 'Mexico City',
      countryCode: 'MX',
    },
    { iataCode: 'ATH', name: 'Athens International', cityName: 'Athens', countryCode: 'GR' },
    { iataCode: 'IST', name: 'Istanbul Airport', cityName: 'Istanbul', countryCode: 'TR' },
    { iataCode: 'CMN', name: 'Casablanca Mohammed V', cityName: 'Casablanca', countryCode: 'MA' },
    { iataCode: 'PMI', name: 'Palma de Mallorca', cityName: 'Palma', countryCode: 'ES' },
  ]

  const q = query?.toLowerCase() ?? ''
  const filtered = STATIC.filter(
    a =>
      a.iataCode.toLowerCase().includes(q) ||
      a.cityName.toLowerCase().includes(q) ||
      a.name.toLowerCase().includes(q)
  ).slice(0, 8)

  return {
    meta: { count: filtered.length, links: { self: '' } },
    data: filtered.map(a => ({
      type: 'location',
      subType: 'AIRPORT',
      name: a.name,
      detailedName: `${a.name}, ${a.countryCode}`,
      id: `T${a.iataCode}`,
      iataCode: a.iataCode,
      address: {
        cityName: a.cityName,
        cityCode: a.iataCode,
        countryCode: a.countryCode,
      },
      analytics: { flights: { score: 50 }, travelers: { score: 50 } },
    })),
  }
}
