/**
 * Mock data in Duffel API response format.
 * Used when DUFFEL_ACCESS_TOKEN is not set, or VITE_MOCK_API=true in the frontend.
 */

const TODAY = new Date()
const dt = (daysOffset, hour = 8, min = 0) => {
  const d = new Date(TODAY)
  d.setDate(d.getDate() + daysOffset)
  d.setHours(hour, min, 0, 0)
  return d.toISOString().slice(0, 19)
}

// Airline name lookup
const AIRLINES = {
  IB: 'Iberia',
  VY: 'Vueling',
  FR: 'Ryanair',
  U2: 'easyJet',
  BA: 'British Airways',
  AF: 'Air France',
  LH: 'Lufthansa',
  KL: 'KLM',
  EK: 'Emirates',
  QR: 'Qatar Airways',
  AA: 'American Airlines',
  UA: 'United Airlines',
  DL: 'Delta Air Lines',
  AY: 'Finnair',
}

// Airport info lookup (for segment labels)
const AIRPORTS = {
  MAD: { name: 'Madrid Barajas', city_name: 'Madrid' },
  BCN: { name: 'Barcelona El Prat', city_name: 'Barcelona' },
  LHR: { name: 'London Heathrow', city_name: 'London' },
  LGW: { name: 'London Gatwick', city_name: 'London' },
  CDG: { name: 'Paris Charles de Gaulle', city_name: 'Paris' },
  AMS: { name: 'Amsterdam Schiphol', city_name: 'Amsterdam' },
  FRA: { name: 'Frankfurt Airport', city_name: 'Frankfurt' },
  MUC: { name: 'Munich Airport', city_name: 'Munich' },
  FCO: { name: 'Rome Fiumicino', city_name: 'Rome' },
  MXP: { name: 'Milan Malpensa', city_name: 'Milan' },
  LIS: { name: 'Lisbon Portela', city_name: 'Lisbon' },
  ZRH: { name: 'Zurich Airport', city_name: 'Zurich' },
  VIE: { name: 'Vienna International', city_name: 'Vienna' },
  JFK: { name: 'New York JFK', city_name: 'New York' },
  LAX: { name: 'Los Angeles International', city_name: 'Los Angeles' },
  DXB: { name: 'Dubai International', city_name: 'Dubai' },
  DOH: { name: 'Hamad International', city_name: 'Doha' },
  SIN: { name: 'Singapore Changi', city_name: 'Singapore' },
  NRT: { name: 'Tokyo Narita', city_name: 'Tokyo' },
  GRU: { name: 'São Paulo Guarulhos', city_name: 'São Paulo' },
  MEX: { name: 'Mexico City International', city_name: 'Mexico City' },
  ATH: { name: 'Athens International', city_name: 'Athens' },
  IST: { name: 'Istanbul Airport', city_name: 'Istanbul' },
  CMN: { name: 'Casablanca Mohammed V', city_name: 'Casablanca' },
  PMI: { name: 'Palma de Mallorca', city_name: 'Palma' },
}

const ap = iata => AIRPORTS[iata] ?? { name: iata, city_name: iata }

/** Build a Duffel-format flight offer */
function offer({
  id,
  origin,
  destination,
  departAt,
  arriveAt,
  carrier,
  flightNum,
  totalPrice,
  currency = 'EUR',
  duration,
  returnDepartAt,
  returnArriveAt,
  returnCarrier,
  returnFlightNum,
  returnDuration,
  aircraft = '320',
}) {
  const carrierName = AIRLINES[carrier] ?? carrier
  const retCarrier = returnCarrier ?? carrier
  const retCarrierName = AIRLINES[retCarrier] ?? retCarrier
  const dur = duration ?? 'PT2H0M'

  const outboundSlice = {
    id: `sli_${id}_out`,
    origin: { iata_code: origin, ...ap(origin) },
    destination: { iata_code: destination, ...ap(destination) },
    duration: dur,
    segments: [
      {
        id: `seg_${id}_out`,
        departing_at: departAt,
        arriving_at: arriveAt,
        origin: { iata_code: origin, ...ap(origin), terminal: null },
        destination: { iata_code: destination, ...ap(destination), terminal: null },
        marketing_carrier: { iata_code: carrier, name: carrierName },
        operating_carrier: { iata_code: carrier, name: carrierName },
        marketing_carrier_flight_number: String(flightNum),
        aircraft: { iata_code: aircraft, name: `Aircraft ${aircraft}` },
        duration: dur,
        stops: [],
      },
    ],
  }

  const slices = [outboundSlice]

  if (returnDepartAt) {
    const retDur = returnDuration ?? dur
    slices.push({
      id: `sli_${id}_ret`,
      origin: { iata_code: destination, ...ap(destination) },
      destination: { iata_code: origin, ...ap(origin) },
      duration: retDur,
      segments: [
        {
          id: `seg_${id}_ret`,
          departing_at: returnDepartAt,
          arriving_at: returnArriveAt,
          origin: { iata_code: destination, ...ap(destination), terminal: null },
          destination: { iata_code: origin, ...ap(origin), terminal: null },
          marketing_carrier: { iata_code: retCarrier, name: retCarrierName },
          operating_carrier: { iata_code: retCarrier, name: retCarrierName },
          marketing_carrier_flight_number: String(returnFlightNum ?? flightNum),
          aircraft: { iata_code: aircraft, name: `Aircraft ${aircraft}` },
          duration: retDur,
          stops: [],
        },
      ],
    })
  }

  return {
    id: `off_${String(id).padStart(7, '0')}`,
    total_amount: String(totalPrice.toFixed(2)),
    total_currency: currency,
    base_amount: String((totalPrice * 0.82).toFixed(2)),
    base_currency: currency,
    slices,
    passengers: [{ id: 'pas_001', type: 'adult' }],
    owner: { iata_code: carrier, name: carrierName },
  }
}

// ── MAD offers ──────────────────────────────────────────────────────────────
const MAD_OFFERS = [
  offer({
    id: 1,
    origin: 'MAD',
    destination: 'BCN',
    departAt: dt(7, 8, 0),
    arriveAt: dt(7, 9, 20),
    carrier: 'VY',
    flightNum: '1820',
    totalPrice: 49,
    duration: 'PT1H20M',
    returnDepartAt: dt(14, 19, 0),
    returnArriveAt: dt(14, 20, 20),
    returnFlightNum: '1823',
    returnDuration: 'PT1H20M',
  }),
  offer({
    id: 2,
    origin: 'MAD',
    destination: 'LIS',
    departAt: dt(7, 9, 30),
    arriveAt: dt(7, 10, 45),
    carrier: 'IB',
    flightNum: '3822',
    totalPrice: 69,
    duration: 'PT1H15M',
    returnDepartAt: dt(14, 12, 0),
    returnArriveAt: dt(14, 13, 15),
  }),
  offer({
    id: 3,
    origin: 'MAD',
    destination: 'LHR',
    departAt: dt(7, 7, 15),
    arriveAt: dt(7, 9, 35),
    carrier: 'IB',
    flightNum: '3170',
    totalPrice: 89,
    duration: 'PT2H20M',
    returnDepartAt: dt(14, 18, 0),
    returnArriveAt: dt(14, 20, 25),
    returnFlightNum: '3171',
    returnDuration: 'PT2H25M',
  }),
  offer({
    id: 4,
    origin: 'MAD',
    destination: 'CDG',
    departAt: dt(7, 6, 50),
    arriveAt: dt(7, 9, 0),
    carrier: 'AF',
    flightNum: '1001',
    totalPrice: 95,
    duration: 'PT2H10M',
    returnDepartAt: dt(14, 15, 0),
    returnArriveAt: dt(14, 17, 15),
    returnCarrier: 'IB',
    returnFlightNum: '3554',
    returnDuration: 'PT2H15M',
  }),
  offer({
    id: 5,
    origin: 'MAD',
    destination: 'FCO',
    departAt: dt(7, 8, 0),
    arriveAt: dt(7, 10, 30),
    carrier: 'IB',
    flightNum: '3460',
    totalPrice: 105,
    duration: 'PT2H30M',
    returnDepartAt: dt(14, 14, 0),
    returnArriveAt: dt(14, 16, 35),
    returnFlightNum: '3461',
  }),
  offer({
    id: 6,
    origin: 'MAD',
    destination: 'AMS',
    departAt: dt(7, 7, 30),
    arriveAt: dt(7, 10, 10),
    carrier: 'KL',
    flightNum: '1705',
    totalPrice: 119,
    duration: 'PT2H40M',
    returnDepartAt: dt(14, 17, 0),
    returnArriveAt: dt(14, 19, 45),
    returnFlightNum: '1706',
    aircraft: '73H',
  }),
  offer({
    id: 7,
    origin: 'MAD',
    destination: 'FRA',
    departAt: dt(7, 6, 40),
    arriveAt: dt(7, 9, 30),
    carrier: 'LH',
    flightNum: '1801',
    totalPrice: 129,
    duration: 'PT2H50M',
    returnDepartAt: dt(14, 16, 0),
    returnArriveAt: dt(14, 19, 0),
    returnFlightNum: '1800',
  }),
  offer({
    id: 8,
    origin: 'MAD',
    destination: 'MXP',
    departAt: dt(7, 9, 0),
    arriveAt: dt(7, 11, 40),
    carrier: 'VY',
    flightNum: '6152',
    totalPrice: 79,
    duration: 'PT2H40M',
    returnDepartAt: dt(14, 13, 0),
    returnArriveAt: dt(14, 15, 45),
    returnFlightNum: '6153',
  }),
  offer({
    id: 9,
    origin: 'MAD',
    destination: 'DXB',
    departAt: dt(7, 22, 30),
    arriveAt: dt(8, 8, 0),
    carrier: 'EK',
    flightNum: '141',
    totalPrice: 389,
    duration: 'PT7H30M',
    returnDepartAt: dt(14, 10, 0),
    returnArriveAt: dt(14, 15, 30),
    returnFlightNum: '142',
    returnDuration: 'PT7H30M',
    aircraft: '388',
  }),
  offer({
    id: 10,
    origin: 'MAD',
    destination: 'JFK',
    departAt: dt(7, 11, 0),
    arriveAt: dt(7, 14, 15),
    carrier: 'IB',
    flightNum: '6251',
    totalPrice: 489,
    duration: 'PT9H15M',
    returnDepartAt: dt(14, 17, 0),
    returnArriveAt: dt(15, 7, 20),
    returnFlightNum: '6252',
    returnDuration: 'PT8H20M',
    aircraft: '333',
  }),
  offer({
    id: 11,
    origin: 'MAD',
    destination: 'GRU',
    departAt: dt(7, 23, 55),
    arriveAt: dt(8, 9, 0),
    carrier: 'IB',
    flightNum: '6841',
    totalPrice: 599,
    duration: 'PT11H5M',
    returnDepartAt: dt(14, 22, 0),
    returnArriveAt: dt(15, 14, 20),
    returnFlightNum: '6842',
    returnDuration: 'PT14H20M',
    aircraft: '333',
  }),
  offer({
    id: 12,
    origin: 'MAD',
    destination: 'MEX',
    departAt: dt(7, 12, 0),
    arriveAt: dt(7, 17, 30),
    carrier: 'IB',
    flightNum: '6403',
    totalPrice: 549,
    duration: 'PT11H30M',
    returnDepartAt: dt(14, 19, 30),
    returnArriveAt: dt(15, 13, 20),
    returnFlightNum: '6404',
    returnDuration: 'PT11H50M',
    aircraft: '340',
  }),
  offer({
    id: 13,
    origin: 'MAD',
    destination: 'NRT',
    departAt: dt(7, 9, 0),
    arriveAt: dt(8, 5, 30),
    carrier: 'IB',
    flightNum: '6017',
    totalPrice: 789,
    duration: 'PT14H30M',
    returnDepartAt: dt(14, 12, 0),
    returnArriveAt: dt(15, 12, 0),
    returnFlightNum: '6018',
    returnDuration: 'PT16H0M',
    aircraft: '333',
  }),
  offer({
    id: 14,
    origin: 'MAD',
    destination: 'PMI',
    departAt: dt(7, 7, 0),
    arriveAt: dt(7, 8, 20),
    carrier: 'VY',
    flightNum: '3930',
    totalPrice: 55,
    duration: 'PT1H20M',
    returnDepartAt: dt(14, 20, 0),
    returnArriveAt: dt(14, 21, 20),
    returnFlightNum: '3931',
  }),
  offer({
    id: 15,
    origin: 'MAD',
    destination: 'ATH',
    departAt: dt(7, 6, 0),
    arriveAt: dt(7, 10, 40),
    carrier: 'IB',
    flightNum: '3680',
    totalPrice: 149,
    duration: 'PT4H40M',
    returnDepartAt: dt(14, 11, 0),
    returnArriveAt: dt(14, 15, 50),
    returnFlightNum: '3681',
  }),
  offer({
    id: 16,
    origin: 'MAD',
    destination: 'IST',
    departAt: dt(7, 7, 0),
    arriveAt: dt(7, 12, 40),
    carrier: 'IB',
    flightNum: '3710',
    totalPrice: 175,
    duration: 'PT5H40M',
    returnDepartAt: dt(14, 14, 0),
    returnArriveAt: dt(14, 20, 10),
    returnFlightNum: '3711',
  }),
  offer({
    id: 17,
    origin: 'MAD',
    destination: 'LAX',
    departAt: dt(7, 11, 0),
    arriveAt: dt(7, 13, 40),
    carrier: 'IB',
    flightNum: '6273',
    totalPrice: 649,
    duration: 'PT14H40M',
    returnDepartAt: dt(14, 16, 0),
    returnArriveAt: dt(15, 13, 50),
    returnFlightNum: '6274',
    returnDuration: 'PT15H50M',
    aircraft: '333',
  }),
  offer({
    id: 18,
    origin: 'MAD',
    destination: 'DOH',
    departAt: dt(7, 7, 30),
    arriveAt: dt(7, 14, 0),
    carrier: 'QR',
    flightNum: '148',
    totalPrice: 349,
    duration: 'PT6H30M',
    returnDepartAt: dt(14, 15, 0),
    returnArriveAt: dt(14, 21, 0),
    returnFlightNum: '149',
    aircraft: '359',
  }),
  offer({
    id: 19,
    origin: 'MAD',
    destination: 'CMN',
    departAt: dt(7, 9, 0),
    arriveAt: dt(7, 10, 30),
    carrier: 'IB',
    flightNum: '3740',
    totalPrice: 89,
    duration: 'PT1H30M',
    returnDepartAt: dt(14, 11, 0),
    returnArriveAt: dt(14, 12, 30),
    returnFlightNum: '3741',
  }),
  offer({
    id: 20,
    origin: 'MAD',
    destination: 'SIN',
    departAt: dt(7, 23, 0),
    arriveAt: dt(8, 17, 20),
    carrier: 'QR',
    flightNum: '148',
    totalPrice: 699,
    duration: 'PT16H20M',
    returnDepartAt: dt(14, 1, 30),
    returnArriveAt: dt(15, 7, 30),
    returnFlightNum: '149',
    returnDuration: 'PT18H0M',
    aircraft: '359',
  }),
]

// ── LHR offers ──────────────────────────────────────────────────────────────
const LHR_OFFERS = [
  offer({
    id: 101,
    origin: 'LHR',
    destination: 'JFK',
    departAt: dt(7, 9, 0),
    arriveAt: dt(7, 12, 0),
    carrier: 'BA',
    flightNum: '117',
    totalPrice: 349,
    currency: 'GBP',
    duration: 'PT8H0M',
    returnDepartAt: dt(14, 18, 30),
    returnArriveAt: dt(15, 6, 40),
    returnFlightNum: '118',
    aircraft: '77W',
  }),
  offer({
    id: 102,
    origin: 'LHR',
    destination: 'CDG',
    departAt: dt(7, 7, 0),
    arriveAt: dt(7, 9, 15),
    carrier: 'BA',
    flightNum: '304',
    totalPrice: 89,
    currency: 'GBP',
    duration: 'PT1H15M',
    returnDepartAt: dt(14, 16, 0),
    returnArriveAt: dt(14, 18, 20),
    returnFlightNum: '307',
  }),
  offer({
    id: 103,
    origin: 'LHR',
    destination: 'DXB',
    departAt: dt(7, 21, 30),
    arriveAt: dt(8, 8, 30),
    carrier: 'EK',
    flightNum: '3',
    totalPrice: 399,
    currency: 'GBP',
    duration: 'PT7H0M',
    returnDepartAt: dt(14, 3, 15),
    returnArriveAt: dt(14, 8, 15),
    returnFlightNum: '4',
    aircraft: '380',
  }),
  offer({
    id: 104,
    origin: 'LHR',
    destination: 'SIN',
    departAt: dt(7, 21, 15),
    arriveAt: dt(8, 17, 15),
    carrier: 'BA',
    flightNum: '11',
    totalPrice: 569,
    currency: 'GBP',
    duration: 'PT12H0M',
    returnDepartAt: dt(14, 23, 45),
    returnArriveAt: dt(15, 6, 15),
    returnFlightNum: '12',
    aircraft: '77W',
  }),
  offer({
    id: 105,
    origin: 'LHR',
    destination: 'AMS',
    departAt: dt(7, 6, 30),
    arriveAt: dt(7, 8, 55),
    carrier: 'BA',
    flightNum: '428',
    totalPrice: 69,
    currency: 'GBP',
    duration: 'PT1H25M',
    returnDepartAt: dt(14, 18, 0),
    returnArriveAt: dt(14, 20, 25),
    returnFlightNum: '433',
  }),
  offer({
    id: 106,
    origin: 'LHR',
    destination: 'NRT',
    departAt: dt(7, 11, 0),
    arriveAt: dt(8, 7, 55),
    carrier: 'BA',
    flightNum: '5',
    totalPrice: 689,
    currency: 'GBP',
    duration: 'PT12H55M',
    returnDepartAt: dt(14, 12, 55),
    returnArriveAt: dt(15, 17, 55),
    returnFlightNum: '6',
    aircraft: '789',
  }),
  offer({
    id: 107,
    origin: 'LHR',
    destination: 'MAD',
    departAt: dt(7, 7, 30),
    arriveAt: dt(7, 10, 55),
    carrier: 'BA',
    flightNum: '460',
    totalPrice: 99,
    currency: 'GBP',
    duration: 'PT2H25M',
    returnDepartAt: dt(14, 11, 30),
    returnArriveAt: dt(14, 15, 0),
    returnFlightNum: '461',
  }),
  offer({
    id: 108,
    origin: 'LHR',
    destination: 'FCO',
    departAt: dt(7, 7, 0),
    arriveAt: dt(7, 10, 25),
    carrier: 'BA',
    flightNum: '550',
    totalPrice: 149,
    currency: 'GBP',
    duration: 'PT2H25M',
    returnDepartAt: dt(14, 12, 30),
    returnArriveAt: dt(14, 15, 55),
    returnFlightNum: '551',
  }),
]

// ── JFK offers ──────────────────────────────────────────────────────────────
const JFK_OFFERS = [
  offer({
    id: 201,
    origin: 'JFK',
    destination: 'LHR',
    departAt: dt(7, 22, 0),
    arriveAt: dt(8, 10, 30),
    carrier: 'AA',
    flightNum: '100',
    totalPrice: 449,
    currency: 'USD',
    duration: 'PT7H30M',
    returnDepartAt: dt(14, 11, 0),
    returnArriveAt: dt(14, 14, 0),
    returnFlightNum: '101',
    aircraft: '77W',
  }),
  offer({
    id: 202,
    origin: 'JFK',
    destination: 'CDG',
    departAt: dt(7, 23, 30),
    arriveAt: dt(8, 13, 15),
    carrier: 'AA',
    flightNum: '44',
    totalPrice: 399,
    currency: 'USD',
    duration: 'PT7H45M',
    returnDepartAt: dt(14, 14, 25),
    returnArriveAt: dt(14, 17, 10),
    returnFlightNum: '45',
    aircraft: '77W',
  }),
  offer({
    id: 203,
    origin: 'JFK',
    destination: 'DXB',
    departAt: dt(7, 22, 0),
    arriveAt: dt(8, 19, 10),
    carrier: 'EK',
    flightNum: '202',
    totalPrice: 699,
    currency: 'USD',
    duration: 'PT13H10M',
    returnDepartAt: dt(14, 21, 30),
    returnArriveAt: dt(15, 3, 55),
    returnFlightNum: '201',
    aircraft: '388',
  }),
  offer({
    id: 204,
    origin: 'JFK',
    destination: 'GRU',
    departAt: dt(7, 20, 0),
    arriveAt: dt(8, 7, 30),
    carrier: 'AA',
    flightNum: '934',
    totalPrice: 529,
    currency: 'USD',
    duration: 'PT9H30M',
    returnDepartAt: dt(14, 10, 0),
    returnArriveAt: dt(14, 21, 55),
    returnFlightNum: '935',
    aircraft: '763',
  }),
  offer({
    id: 205,
    origin: 'JFK',
    destination: 'LAX',
    departAt: dt(7, 6, 0),
    arriveAt: dt(7, 9, 30),
    carrier: 'AA',
    flightNum: '1',
    totalPrice: 149,
    currency: 'USD',
    duration: 'PT5H30M',
    returnDepartAt: dt(14, 11, 0),
    returnArriveAt: dt(14, 19, 25),
    returnFlightNum: '2',
    aircraft: '321',
  }),
  offer({
    id: 206,
    origin: 'JFK',
    destination: 'NRT',
    departAt: dt(7, 12, 30),
    arriveAt: dt(8, 15, 30),
    carrier: 'AA',
    flightNum: '169',
    totalPrice: 799,
    currency: 'USD',
    duration: 'PT14H0M',
    returnDepartAt: dt(14, 17, 0),
    returnArriveAt: dt(15, 17, 0),
    returnFlightNum: '170',
    aircraft: '777',
  }),
  offer({
    id: 207,
    origin: 'JFK',
    destination: 'MEX',
    departAt: dt(7, 7, 0),
    arriveAt: dt(7, 11, 0),
    carrier: 'AA',
    flightNum: '193',
    totalPrice: 299,
    currency: 'USD',
    duration: 'PT4H0M',
    returnDepartAt: dt(14, 12, 0),
    returnArriveAt: dt(14, 17, 25),
    returnFlightNum: '192',
  }),
  offer({
    id: 208,
    origin: 'JFK',
    destination: 'MAD',
    departAt: dt(7, 23, 55),
    arriveAt: dt(8, 11, 40),
    carrier: 'IB',
    flightNum: '6252',
    totalPrice: 519,
    currency: 'USD',
    duration: 'PT7H45M',
    returnDepartAt: dt(14, 11, 0),
    returnArriveAt: dt(14, 14, 15),
    returnFlightNum: '6251',
    aircraft: '333',
  }),
]

const OFFERS_BY_ORIGIN = { MAD: MAD_OFFERS, LHR: LHR_OFFERS, JFK: JFK_OFFERS }

/**
 * Generate mock Duffel-format response.
 * Used by api/offers.js (server) and src/features/flights/api.js (VITE_MOCK_API=true).
 */
export function mockOffersResponse({ origin, destination }) {
  const o = origin?.toUpperCase()
  let results = OFFERS_BY_ORIGIN[o] ?? MAD_OFFERS

  if (destination) {
    const dest = destination.toUpperCase()
    results = results.filter(off =>
      off.slices[0]?.segments?.some(s => s.destination.iata_code === dest)
    )
  }

  // Add slight price variance for realism
  const varied = results.map(off => ({
    ...off,
    total_amount: String((parseFloat(off.total_amount) * (0.92 + Math.random() * 0.16)).toFixed(2)),
  }))

  return { data: varied }
}

/**
 * Generate mock airport locations response for autocomplete.
 * Returns format compatible with AirportAutocomplete.jsx.
 */
export function mockLocationsResponse(query) {
  const STATIC = Object.entries(AIRPORTS).map(([iata, info]) => ({
    iataCode: iata,
    name: info.name,
    cityName: info.city_name,
    countryCode: '',
  }))

  const q = query?.toLowerCase() ?? ''
  return {
    data: STATIC.filter(
      a =>
        a.iataCode.toLowerCase().includes(q) ||
        a.cityName.toLowerCase().includes(q) ||
        a.name.toLowerCase().includes(q)
    ).slice(0, 8),
  }
}
